/**
 * CircuitSage AI — Shared Constants and Types
 */

const EPISTEMIC_STATUS = {
  VERIFIED_FACT: 'VERIFIED_FACT',
  AI_INFERENCE: 'AI_INFERENCE',
  UNKNOWN: 'UNKNOWN'
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',
  RETRIEVAL_FAILURE: 'RETRIEVAL_FAILURE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

const SUPPORTED_BOARDS = [
  'ESP32 DevKit v1',
  'Arduino Uno R3',
  'Raspberry Pi Pico'
];

module.exports = {
  EPISTEMIC_STATUS,
  ERROR_CODES,
  SUPPORTED_BOARDS
};
